
jwt:
  secretKey: "26462948404D635166546A576E5A7234753778214125442A472D4B614E645267"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/digitalguil?serverTimezone=Asia/Seoul
    username: connecter
    password: connect1@2@34

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
