

jwt:
  secretKey: "26462948404D635166546A576E5A7234753778214125442A472D4B614E645267"
  expirationHours: 24
  issuer: lime

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.50.174.34:3306/digitalguil?serverTimezone=Asia/Seoul
    username: connecter
    password: connect1@2@34

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      kakao:
        grantType: authorization_code
        clientId: 78f9db867e8831b570efd5e479f72a08
        clientSecret: OVrR5jRNXuVhuiH6eSpPB6SGHhsmCRlu
        #TODO 배포시 리다이렉트 주소 변경해야함
        redirectUri: http://49.50.174.34:8080/api/login/callback
        clientName: Kakao
        clientAuthenticationMethod: POST
        authorizationUri: https://kauth.kakao.com/oauth/authorize
        tokenUri: https://kauth.kakao.com/oauth/token
        userInfoUri: https://kapi.kakao.com/v2/user/me
        userNameAttribute: id
      naver:
        grantType: authorization_code
        clientId: sQUbWJL0mJ0oFmSGbcbD
        clientSecret: NSNmc2Z1AT
        #TODO 배포시 리다이렉트 주소 변경해야함
        redirectUri: http://49.50.174.34/:8080/api/login/callback/naver
        clientName: Naver
        clientAuthenticationMethod: POST
        authorizationUri: https://nid.naver.com/oauth2.0/authorize
        tokenUri: https://nid.naver.com/oauth2.0/token
        userInfoUri: https://openapi.naver.com/v1/nid/me
        userNameAttribute: id

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
