# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - main 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTION_TOKEN }}
        submodules: 'recursive'
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Copy file via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.DEPLOYMENT_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "*.jar"
          target: "~/cicd"

      - name: Execute remote SSH commands to restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.DEPLOYMENT_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |          
            # Stop your server (modify this command to fit your server)
            sudo systemctl stop myapp

            rm ~/cicd/app.jar

            # Move the JAR
            mv ~/cicd/*.jar ~/cicd/app.jar

            # Start your server (modify this command to fit your server)
            sudo systemctl start myapp
